# Generated by Django 5.1.3 on 2024-11-19 10:27

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0003_rename_show_theme_astronomyshow_show_themes"),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(
                null=True, upload_to=planetarium.models.astronomy_show_image_path
            ),
        ),
    ]
