# Generated by Django 5.1.3 on 2024-11-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0004_astronomyshow_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astronomyshow",
            name="show_themes",
            field=models.ManyToManyField(blank=True, to="planetarium.showtheme"),
        ),
    ]
