# Generated by Django 5.1.3 on 2024-11-21 12:19

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0005_alter_astronomyshow_show_themes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=planetarium.models.astronomy_show_image_path,
            ),
        ),
    ]
